// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwk.proto

package com.delight.gaia.auth.api.dto.response;

public final class JwkOuterClass {
  private JwkOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_delight_gaia_auth_api_dto_response_Jwk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_delight_gaia_auth_api_dto_response_Jwk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tjwk.proto\022&com.delight.gaia.auth.api.d" +
      "to.response\"{\n\003Jwk\022\013\n\003kty\030\001 \001(\t\022\013\n\003kid\030\002" +
      " \001(\t\022\020\n\003use\030\003 \001(\tH\000\210\001\001\022\016\n\001h\030\004 \001(\tH\001\210\001\001\022\016" +
      "\n\001n\030\005 \001(\tH\002\210\001\001\022\016\n\001e\030\006 \001(\tH\003\210\001\001B\006\n\004_useB\004" +
      "\n\002_hB\004\n\002_nB\004\n\002_eB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_delight_gaia_auth_api_dto_response_Jwk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_delight_gaia_auth_api_dto_response_Jwk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_delight_gaia_auth_api_dto_response_Jwk_descriptor,
        new String[] { "Kty", "Kid", "Use", "H", "N", "E", "Use", "H", "N", "E", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
