// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_type.proto

package com.delight.gaia.base.vo.proto;

public interface BoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.delight.gaia.base.vo.proto.Bool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
