// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaia_message.proto

package com.delight.gaia.base.vo.proto;

public final class GaiaMessage {
  private GaiaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_delight_gaia_base_vo_proto_GaiaMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_delight_gaia_base_vo_proto_GaiaMessageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_delight_gaia_base_vo_proto_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_delight_gaia_base_vo_proto_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_delight_gaia_base_vo_proto_Metadata_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_delight_gaia_base_vo_proto_Metadata_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022gaia_message.proto\022\036com.delight.gaia.b" +
      "ase.vo.proto\"p\n\020GaiaMessageProto\022:\n\010meta" +
      "data\030\001 \001(\0132(.com.delight.gaia.base.vo.pr" +
      "oto.Metadata\022\024\n\007payload\030\002 \001(\014H\000\210\001\001B\n\n\010_p" +
      "ayload\"\243\002\n\010Metadata\022\017\n\002id\030\002 \001(\004H\000\210\001\001\022\024\n\007" +
      "command\030\001 \001(\tH\001\210\001\001\022\033\n\016statusResponse\030\003 \001" +
      "(\rH\002\210\001\001\022\032\n\rerrorResponse\030\004 \001(\tH\003\210\001\001\022L\n\na" +
      "ttributes\030\005 \003(\01328.com.delight.gaia.base." +
      "vo.proto.Metadata.AttributesEntry\0321\n\017Att" +
      "ributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B\005\n\003_idB\n\n\010_commandB\021\n\017_statusRespon" +
      "seB\020\n\016_errorResponseB\004H\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_delight_gaia_base_vo_proto_GaiaMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_delight_gaia_base_vo_proto_GaiaMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_delight_gaia_base_vo_proto_GaiaMessageProto_descriptor,
        new String[] { "Metadata", "Payload", "Payload", });
    internal_static_com_delight_gaia_base_vo_proto_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_delight_gaia_base_vo_proto_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_delight_gaia_base_vo_proto_Metadata_descriptor,
        new String[] { "Id", "Command", "StatusResponse", "ErrorResponse", "Attributes", "Id", "Command", "StatusResponse", "ErrorResponse", });
    internal_static_com_delight_gaia_base_vo_proto_Metadata_AttributesEntry_descriptor =
      internal_static_com_delight_gaia_base_vo_proto_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_com_delight_gaia_base_vo_proto_Metadata_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_delight_gaia_base_vo_proto_Metadata_AttributesEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
