// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaia_message.proto

package com.delight.gaia.base.vo.proto;

public interface GaiaMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.delight.gaia.base.vo.proto.GaiaMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.delight.gaia.base.vo.proto.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.com.delight.gaia.base.vo.proto.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  Metadata getMetadata();
  /**
   * <code>.com.delight.gaia.base.vo.proto.Metadata metadata = 1;</code>
   */
  MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>optional bytes payload = 2;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>optional bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
