// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_type.proto

package com.delight.gaia.base.vo.proto;

public interface I64OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.delight.gaia.base.vo.proto.I64)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional uint64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
