// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaia_message.proto

package com.delight.gaia.base.vo.proto;

public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.delight.gaia.base.vo.proto.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string command = 1;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The command.
   */
  String getCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>optional uint32 statusResponse = 3;</code>
   * @return Whether the statusResponse field is set.
   */
  boolean hasStatusResponse();
  /**
   * <code>optional uint32 statusResponse = 3;</code>
   * @return The statusResponse.
   */
  int getStatusResponse();

  /**
   * <code>optional string errorResponse = 4;</code>
   * @return Whether the errorResponse field is set.
   */
  boolean hasErrorResponse();
  /**
   * <code>optional string errorResponse = 4;</code>
   * @return The errorResponse.
   */
  String getErrorResponse();
  /**
   * <code>optional string errorResponse = 4;</code>
   * @return The bytes for errorResponse.
   */
  com.google.protobuf.ByteString
      getErrorResponseBytes();

  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  boolean containsAttributes(
      String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  java.util.Map<String, String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  /* nullable */
String getAttributesOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  String getAttributesOrThrow(
      String key);
}
